"""add_sch_name_to_student

Revision ID: 04b2520d2763
Revises: a4a375b385fe
Create Date: 2025-12-12 13:12:35.939683

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04b2520d2763'
down_revision = 'a4a375b385fe'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('sch_name', sa.String(), nullable=True))
    op.drop_index('ix_students_reg_no', table_name='students')
    op.create_index(op.f('ix_students_reg_no'), 'students', ['reg_no'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_students_reg_no'), table_name='students')
    op.create_index('ix_students_reg_no', 'students', ['reg_no'], unique=False)
    op.drop_column('students', 'sch_name')
    # ### end Alembic commands ###