"""add_unique_constraint_to_student_reg_no

Revision ID: a4a375b385fe
Revises: ca7e06c199ac
Create Date: 2025-12-12 13:10:17.151203

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4a375b385fe'
down_revision = 'ca7e06c199ac'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###