"""rename_fields_schnm_to_schnum_and_state_name

Revision ID: b76b6b8870af
Revises: bd0bdc3958e8
Create Date: 2025-12-12 10:29:16.866709

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b76b6b8870af'
down_revision = 'bd0bdc3958e8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('schools', 'schnm', new_column_name='schnum')
    op.drop_index('ix_schools_schnm', table_name='schools')
    op.create_index(op.f('ix_schools_schnum'), 'schools', ['schnum'], unique=True)
    
    op.alter_column('states', 'name', new_column_name='state')
    
    op.alter_column('students', 'schnm', new_column_name='schnum')
    op.drop_index('idx_batch_school_reg', table_name='students')
    op.create_index('idx_batch_school_reg', 'students', ['batch', 'schnum', 'reg_no'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('students', 'schnum', new_column_name='schnm')
    op.drop_index('idx_batch_school_reg', table_name='students')
    op.create_index('idx_batch_school_reg', 'students', ['batch', 'schnm', 'reg_no'], unique=False)
    
    op.alter_column('states', 'state', new_column_name='name')
    
    op.alter_column('schools', 'schnum', new_column_name='schnm')
    op.drop_index(op.f('ix_schools_schnum'), table_name='schools')
    op.create_index('ix_schools_schnm', 'schools', ['schnm'], unique=True)
    # ### end Alembic commands ###