"""Initial migration

Revision ID: bd0bdc3958e8
Revises: 
Create Date: 2025-12-11 21:31:40.048541

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd0bdc3958e8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('states',
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('schools_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('schools',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('schnm', sa.String(), nullable=False),
    sa.Column('sch_name', sa.String(), nullable=False),
    sa.Column('state_code', sa.String(), nullable=False),
    sa.Column('state_name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['state_code'], ['states.code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_schools_schnm'), 'schools', ['schnm'], unique=True)
    op.create_table('students',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('batch', sa.String(), nullable=False),
    sa.Column('schnm', sa.String(), nullable=False),
    sa.Column('reg_no', sa.String(), nullable=False),
    sa.Column('ser_no', sa.String(), nullable=False),
    sa.Column('cand_name', sa.String(), nullable=False),
    sa.Column('school_id', sa.UUID(), nullable=True),
    sa.Column('photo_path', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_batch_school_reg', 'students', ['batch', 'schnm', 'reg_no'], unique=False)
    op.create_index(op.f('ix_students_reg_no'), 'students', ['reg_no'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_students_reg_no'), table_name='students')
    op.drop_index('idx_batch_school_reg', table_name='students')
    op.drop_table('students')
    op.drop_index(op.f('ix_schools_schnm'), table_name='schools')
    op.drop_table('schools')
    op.drop_table('states')
    # ### end Alembic commands ###