"""rename_state_code_to_state_and_schools_count_to_schools

Revision ID: ca7e06c199ac
Revises: b76b6b8870af
Create Date: 2025-12-12 10:50:39.959171

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca7e06c199ac'
down_revision = 'b76b6b8870af'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('schools', 'state_code', new_column_name='state')
    op.alter_column('states', 'schools_count', new_column_name='schools')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('states', 'schools', new_column_name='schools_count')
    op.alter_column('schools', 'state', new_column_name='state_code')
    # ### end Alembic commands ###