"""add_nin_to_student

Revision ID: d7b6cd6791dd
Revises: bcb096f1ca91
Create Date: 2026-06-05 12:44:18.564575

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7b6cd6791dd'
down_revision = 'bcb096f1ca91'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('nin', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'nin')
    # ### end Alembic commands ###